### ISSUE TITLE
Edge浏览器可以支持一下吗？

### ISSUE THREAD

**Issue by rachpt** [lei4519/extract-chrome-cookies#1]
cookie 路径：将chrome的 path `/Library/Application Support/Google/Chrome/` 替换为 `/Library/Application Support/Microsoft Edge/`

**Comment by lei4519** [comment]
支持使用 -p 指定 profile 的路径，可以尝试一下能否解决？

**Comment by rachpt** [comment]
感谢回复！
-p设置，路径好像是可以，但是提示：`Decrypt Failed: InvalidPadding`

看了一下代码：好像需要修改 keytar 获取的秘钥。
https://github.com/lei4519/extract-chrome-cookies/blob/7f124e3c199941d86393ae54ee509a2b68823ea2/src/main.rs#L306C22-L306C28

正常可能需要这样写：
<img width="657" alt="image" src="https://github.com/lei4519/extract-chrome-cookies/assets/25758867/d0e5ad85-9cf7-4596-baf2-276bc441d2a4">

```javascript
if (browser === 'chrome') {
  osxKeyService = 'Chrome Safe Storage'
  osxKeyUser = 'Chrome'
} else if (browser === 'edge') {
  osxKeyService = 'Microsoft Edge Safe Storage'
  osxKeyUser = 'Microsoft Edge'
}
```

**Comment by lei4519** [comment]
closed by https://github.com/lei4519/extract-chrome-cookies/pull/2
